spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://db_user:Tharaka123@ac-jtq9t9g-shard-00-00.16ewnrh.mongodb.net:27017,ac-jtq9t9g-shard-00-01.16ewnrh.mongodb.net:27017,ac-jtq9t9g-shard-00-02.16ewnrh.mongodb.net:27017/?ssl=true&replicaSet=atlas-mil11p-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=smartcampus

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=461070201433-c3obgh3qd91kjri2u9v6olsqv4ekclb3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT Configuration
smartcampus.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smartcampus.jwt.expiration=86400000
